gui:
  expandFocusedSidePanel: true
  showIcons: true
  theme:
    selectedLineBgColor:
      - black
      - bold
    selectedRangeBgColor:
      - black
      - bold
  border: 'rounded'
git:
  paging:
    colorArgs: always
    pager: delta --dark --paging=never
