gui:
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  border: 'rounded'
  theme:
    selectedLineBgColor:
      - black
      - bold
    selectedRangeBgColor:
      - green
      - bold
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
