# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
gui:
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  border: "rounded"
  theme:
    selectedLineBgColor:
      - black
      - bold
    selectedRangeBgColor:
      - green
      - bold
git:
  paging:
    colorArg: always
    # pager: delta --dark --paging=never

os:
  editPreset: "emacs"
