gui:
  expandFocusedSidePanel: true
  showIcons: true
  theme:
    selectedLineBgColor:
      - black
      - bold
    selectedRangeBgColor:
      - black
      - bold
  border: "rounded"
os:
  openCommand: "xdg-open {{filename}} >/dev/null"
