return {
	cmdline = { enabled = false },
	messages = { enabled = false, view_search = "virtualtext" },
	popupmenu = { enabled = true, backend = "cmp" },
	notify = { enabled = false },
	lsp = {
		progress = { enabled = false },
		override = {
			["vim.lsp.util.convert_input_to_markdown_lines"] = true,
			["vim.lsp.util.stylize_markdown"] = true,
			["cmp.entry.get_documentation"] = false,
		},
		hover = { enabled = false },
		signature = {
			enabled = true,
			auto_open = {
				enabled = true,
				trigger = true,
				luasnip = true,
				throttle = 50,
			},
		},
		message = { enabled = true },
		documentation = { enabled = false },
	},
	markdown = { enabled = true },
	health = { checker = true },
	smart_move = { enabled = false },
	presets = {
		bottom_search = false,
		command_palette = false,
		long_message_to_split = true,
		inc_rename = false,
		lsp_doc_border = true,
	},
	throttle = 1000 / 30,
	views = {},
	routes = {},
	status = {},
	format = {},
}
